### ISSUE TITLE
Version 0.4.3 not installing from PyPI on Ubuntu 16.04 LTS/pip3

### ISSUE THREAD

**Issue by d20tech** [eyeseast/python-frontmatter#41]
It looks like the 0.4.3 release was published using a MacOS specific version identifier. Attempting to install on Linux with:

`pip3 install python-frontmatter`

is pulling 0.4.2 when 0.4.3 should be available. However, trying to force it to use 0.4.3 with:

`pip3 install python-frontmatter==0.4.3`

fails with this error:

```Collecting python-frontmatter==0.4.3
  Could not find a version that satisfies the requirement python-frontmatter==0.4.3 (from versions: 0.3.0.macosx-10.10-intel, 0.3.1.macosx-10.10-intel, 0.4.3.macosx-10.13-intel, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.1, 0.3.1, 0.4.0, 0.4.1, 0.4.2)
No matching distribution found for python-frontmatter==0.4.3
```

Attempting to install with the full version string causes pip3 to blow up:

```$ pip3 install python-frontmatter==0.4.3.macosx-10.13-intel
Collecting python-frontmatter==0.4.3.macosx-10.13-intel
  Downloading https://files.pythonhosted.org/packages/b1/21/43a9f9a8f3f91201102350ccb98c4cecfa697379c9c7262f7a80db63744e/python-frontmatter-0.4.3.macosx-10.13-intel.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/sean/Source/d20tech/pipes/virtualenv/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-az_55ceg/python-frontmatter/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-az_55ceg/python-frontmatter/
```

**Comment by eyeseast** [comment]
Just pushed `v0.4.4`. Please test and see if that works better.

**Comment by d20tech** [comment]
Version 0.4.4 installs as expected. Thanks!
