### ISSUE TITLE
test: Add a HandlerBaseTest

### ISSUE THREAD

**Issue by NGenetzky** [eyeseast/python-frontmatter#46]
Add a base test that can be inherited and then `setUp()` in different ways to easily exercise the functions that `frontmatter.handlers` are supposed to implement.

**Comment by eyeseast** [comment]
Yes please.

**Comment by eyeseast** [comment]
All yours. Thank you.

**Comment by NGenetzky** [comment]
Was pretty simple. Identified a few things that I personally consider bugs, but in these cases I only identified them in the test - no changes made to the code.

I did reveal a pretty significant bug with JSON loader with the following test (which is testing the handler through functions in the package).

```
    def test_external(self):
        filename = self.data['filename']
        content = self.data['content']
        metadata = self.data['metadata']

        # TODO: fronmatter.load() is stripping whitespace!
        content_stripped = content.strip()

        post = frontmatter.load(filename)

        self.assertEqual(post.content, content_stripped)
        for k, v in metadata.items():
            self.assertEqual(post[k], v)

        # dumps and then loads to ensure round trip conversions.
        posttext = frontmatter.dumps(post, handler=self.handler)
        post_2 = frontmatter.loads(posttext)

        for k in post.metadata:
            self.assertEqual(post.metadata[k], post_2.metadata[k])

        self.assertEqual(post.content, post_2.content)
```

Reveals:

```
======================================================================
ERROR: test_external (__main__.JSONHandlerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 375, in test_external
    post_2 = frontmatter.loads(posttext)
  File "/home/ngenetzky/git/ngenetzky/python-frontmatter/frontmatter/__init__.py", line 129, in loads
    metadata, content = parse(text, encoding, handler, **defaults)
  File "/home/ngenetzky/git/ngenetzky/python-frontmatter/frontmatter/__init__.py", line 87, in parse
    fm = handler.load(fm)
  File "/home/ngenetzky/git/ngenetzky/python-frontmatter/frontmatter/default_handlers.py", line 235, in load
    return json.loads(fm, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)
```
The error becomes clear when I printed the `dumps`:
```
-------------------------------------------------------------------------------- post
Title
=====

title2
------

Hello.

Just need three dashes
---

And this might break.
--------------------------------------------------------------------------------


-------------------------------------------------------------------------------- posttext
{
{"something": "else", "test": "tester", "author": "bob"}
}

Title
=====

title2
------

Hello.

Just need three dashes
---

And this might break.
--------------------------------------------------------------------------------
```

**Comment by eyeseast** [comment]
Done via #51
